name: VersionCheckerX
version: '2.2'
main: io.github.vinesh27.versioncheckerx.VersionCheckerX
api-version: 1.18
authors: [ vinesh27, Bastaboii ]
description: Version Checker is a plugin that can check for all the plugins in your server and inform if a plugin is outdated
commands:
  versionChecker:
    description: Used to check the versions of plugins
    usage: <command>